# Generated by Django 5.2.6 on 2025-09-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='upload/')),
            ],
        ),
        migrations.RemoveField(
            model_name='galleryimage',
            name='image_url',
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='image_file',
            field=models.ImageField(default=1, upload_to='gallery/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='testimonials/'),
        ),
    ]
