# Generated by Django 5.2.6 on 2025-09-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_contactinquiry_equipmentcategory_feature_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryimage',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='galleryimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='galleryimage',
            name='quote',
        ),
        migrations.RemoveField(
            model_name='galleryimage',
            name='title',
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='image_caption',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='image_title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
