# Generated by Django 5.2.6 on 2025-09-17 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_remove_galleryimage_caption_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryimage',
            name='image_caption',
        ),
        migrations.RemoveField(
            model_name='galleryimage',
            name='image_file',
        ),
        migrations.RemoveField(
            model_name='galleryimage',
            name='image_title',
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='caption',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(default=2, upload_to='gallery/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='quote',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
