# Generated by Django 5.2.6 on 2025-09-17 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_remove_galleryimage_image_caption_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galleryimage',
            old_name='image',
            new_name='image_file',
        ),
        migrations.RemoveField(
            model_name='fitnessclass',
            name='image_url',
        ),
        migrations.AddField(
            model_name='fitnessclass',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='fitness_classes/'),
        ),
    ]
