# Generated by Django 5.2.6 on 2025-09-19 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_plan_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='membership',
            field=models.CharField(max_length=20),
        ),
    ]
