# Generated by Django 5.2.6 on 2025-09-19 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_alter_plan_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='membership',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.CharField(max_length=30),
        ),
    ]
