# Generated by Django 5.2.6 on 2025-09-19 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_alter_plan_membership_alter_plan_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnessclass',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='classes/'),
        ),
    ]
