# Generated by Django 5.2.6 on 2025-11-07 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_member_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AlterField(
            model_name='fitnessclass',
            name='category',
            field=models.CharField(blank=True, help_text='(legacy) free-text category', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fitnessclass',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='fitnessclass',
            name='category_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='mainapp.category'),
        ),
    ]
