# Generated by Django 5.2.6 on 2025-11-07 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_remove_category_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='contactinquiry',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='equipmentcategory',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='feature',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='fitnessclass',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['-join_date']},
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='herosection',
            name='subtitle',
            field=models.CharField(blank=True, default='Your Fitness Journey Starts Here', max_length=300),
        ),
        migrations.AddField(
            model_name='herosection',
            name='title',
            field=models.CharField(blank=True, default='Welcome to Our Gym', max_length=200),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='fitnessclass',
            name='category',
            field=models.CharField(blank=True, help_text='(Legacy) Free-text category; will be replaced by Category FK.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fitnessclass',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
