# Generated by Django 5.2.6 on 2025-11-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_alter_category_options_alter_contactinquiry_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image/cover for the category tile', null=True, upload_to='category/'),
        ),
    ]
