# Generated by Django 5.2.6 on 2025-11-26 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_category_description_alter_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpiPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('upi_ref', models.CharField(max_length=100)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='upi_screenshots/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('fitness_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.fitnessclass')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.member')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.plan')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
