# Generated by Django 5.2.6 on 2025-11-30 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_upipayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='hero_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='upload/'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='hero_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='upload/'),
        ),
    ]
