# Generated by Django 5.2.6 on 2025-12-05 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_herosection_hero_image_2_herosection_hero_image_3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnessclass',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='fitnessclass/'),
        ),
    ]
