# Generated by Django 5.2.6 on 2025-12-05 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_alter_fitnessclass_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnessclass',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='fitness_class/'),
        ),
    ]
