# Generated by Django 5.2.6 on 2025-12-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0023_alter_fitnessclass_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnessclass',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='fitnessclass/'),
        ),
    ]
